baseURL: https://powei.org
languageCode: en-us
title: Testing
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Sup bruh 😎 this is a test
    Content: This is something shows in your homepage.

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/xflash96"
    - name: "twitter"
      url: "https://x.com/_powei"
    - name: "rss"
      url: "https://powei.org/index.xml"
  ShowReadingTime: true
  author: "Po-Wei Wang"
  contact: "xflash96@gmail.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

  #Google Analytics 4 optional
  env: #production
  GoogleAnalytics: "G-26SJ4Y8M7J"
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

  math: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20


markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
        enable: true
